In [1]:
%config IPcompleter.use_jedi=False

In [9]:
import numpy as np

def sigmoid(x):
    return 1.0/(1+ np.exp(-x))

def sigmoid_derivative(x):
    return x * (1.0 - x)

def mse_loss(y_true, y_pred):
  # y_true and y_pred are numpy arrays of the same length.
  return ((y_true - y_pred) ** 2).mean()

def mse_loss_derivative(y_true, y_pred):
  # y_true and y_pred are numpy arrays of the same length.
  return (2*(y_true - y_pred))

class Heart_disease:
    def __init__(self, x, y):
        self.IN      = x
        #initialize weights with random values
        self.W1   = np.random.rand(self.IN.shape[1],6) 
        self.W2   = np.random.rand(6,4)                 
        self.W3   = np.random.rand(4,1)
        self.y          = y
        self.OUT     = np.zeros(self.y.shape)
        self.learning_rate = 0.3
        
    def feed_forward(self):
        self.HIDDEN_LAYER_1 = sigmoid(np.dot(self.IN, self.W1))
        self.HIDDEN_LAYER_2 = sigmoid(np.dot(self.HIDDEN_LAYER_1, self.W2))
        self.output = sigmoid(np.dot(self.HIDDEN_LAYER_2, self.W3))

    def back_propagate(self):
        # application of the chain rule to find derivative of the loss function with respect to W3, W2 and W1
        print(self.HIDDEN_LAYER_1.T)
        print(self.HIDDEN_LAYER_2.T)
        d_W3 = np.dot(self.HIDDEN_LAYER_2.T, (mse_loss_derivative(self.y, self.output) * sigmoid_derivative(self.output)))
        print(d_W3.shape)
        d_W2 = np.dot(self.HIDDEN_LAYER_1.T,  (np.dot(mse_loss_derivative(self.y, self.output) * sigmoid_derivative(self.output), self.W3.T) * sigmoid_derivative(self.HIDDEN_LAYER_2)))
        print(d_W2.shape)
        d_W1 = np.dot(self.IN.T, np.dot((np.dot(mse_loss_derivative(self.y, self.output) * sigmoid_derivative(self.output), self.W3.T) * sigmoid_derivative(self.HIDDEN_LAYER_2)), self.W2.T) * sigmoid_derivative(self.HIDDEN_LAYER_1))
        print(d_W1.shape)
        # update the weights with the derivative (slope) of the loss function
        self.W1 += self.learning_rate*d_W1
        self.W2 += self.learning_rate*d_W2
        self.W3 += self.learning_rate*d_W3
        
    def train(self, epochs,learning_rate):
        self.learning_rate=learning_rate
        for i in range(epochs):
            self.feed_forward()
            self.back_propagate()
        print("Successfully Trained the Model")
        print("Weights 1:", self.W1)
        print("Weights 2:", self.W2)
        print("Weights 3:", self.W2)
        
    def print_output(self):
        print(self.output)



In [10]:
import pandas as pd

In [11]:
df = pd.read_csv('heart_disease_dataset.csv', sep = ';')

In [12]:
df.head()

age  sex  chest_pain_type  resting_blood_pressure  cholesterol  \
0   63    1                3                     145          233   
1   37    1                2                     130          250   
2   41    0                1                     130          204   
3   56    1                1                     120          236   
4   57    0                0                     120          354   

   fasting_blood_sugar  rest_ecg  max_heart_rate_achieved  \
0                    1         0                      150   
1                    0         1                      187   
2                    0         0                      172   
3                    0         1                      178   
4                    0         1                      163   

   exercise_induced_angina  st_depression  st_slope  num_major_vessels  \
0                        0            2.3         0                  0   
1                        0            3.5         0                  0   
2                        0            1.4         2                  0   
3                        0            0.8         2                  0   
4                        1            0.6         2                  0   

   thalassemia  target  
0            1       1  
1            2       1  
2            2       1  
3            2       1  
4            2       1

In [13]:
df.shape

(303, 14)

In [14]:
df.columns

Index(['age', 'sex', 'chest_pain_type', 'resting_blood_pressure',
       'cholesterol', 'fasting_blood_sugar', 'rest_ecg',
       'max_heart_rate_achieved', 'exercise_induced_angina', 'st_depression',
       'st_slope', 'num_major_vessels', 'thalassemia', 'target'],
      dtype='object')

In [16]:
X = df.drop(["target"],axis=1)
y = df["target"]
y=np.array(y)
y= np.reshape(y, (-1,1)) 
epochs = 2
learning_rate = 0.5
ann = Heart_disease(X,y)
ann.train(epochs, learning_rate)

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
[[0.91053963 0.91053963 0.91053963 ... 0.91053963 0.91053963 0.91053963]
 [0.94733176 0.94733176 0.94733176 ... 0.94733176 0.94733176 0.94733176]
 [0.92080196 0.92080196 0.92080196 ... 0.92080196 0.92080196 0.92080196]
 [0.97923655 0.97923655 0.97923655 ... 0.97923655 0.97923655 0.97923655]]
(4, 1)
(6, 4)
(13, 6)
[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
[[0.37382848 0.37382848 0.37382848 ... 0.37382848 0.37382848 0.37382848]
 [0.7701594  0.7701594  0.7701594  ... 0.7701594  0.7701594  0.7701594 ]
 [0.43545672 0.43545672 0.43545672 ... 0.43545672 0.43545672 0.43545672]
 [0.97218913 0.97218913 0.97218913 ... 0.97218913 0.97218913 0.97218913]]
(4, 1)
(6, 4)
(13, 6)
Successfully Trained the Model
Weights 1: [[0.01536838 0.47470557 0.

In [17]:
ann.print_output()

[[3.40779909e-07]
 [3.40779909e-07]
 [3.40779909e-07]
 [3.40779909e-07]
 [3.40779909e-07]
 [3.40779909e-07]
 [3.40779909e-07]
 [3.40779909e-07]
 [3.40779909e-07]
 [3.40779909e-07]
 [3.40779909e-07]
 [3.40779909e-07]
 [3.40779909e-07]
 [3.40779909e-07]
 [3.40779909e-07]
 [3.40779909e-07]
 [3.40779909e-07]
 [3.40779909e-07]
 [3.40779909e-07]
 [3.40779909e-07]
 [3.40779909e-07]
 [3.40779909e-07]
 [3.40779909e-07]
 [3.40779909e-07]
 [3.40779909e-07]
 [3.40779909e-07]
 [3.40779909e-07]
 [3.40779909e-07]
 [3.40779909e-07]
 [3.40779909e-07]
 [3.40779909e-07]
 [3.40779909e-07]
 [3.40779909e-07]
 [3.40779909e-07]
 [3.40779909e-07]
 [3.40779909e-07]
 [3.40779909e-07]
 [3.40779909e-07]
 [3.40779909e-07]
 [3.40779909e-07]
 [3.40779909e-07]
 [3.40779909e-07]
 [3.40779909e-07]
 [3.40779909e-07]
 [3.40779909e-07]
 [3.40779909e-07]
 [3.40779909e-07]
 [3.40779909e-07]
 [3.40779909e-07]
 [3.40779909e-07]
 [3.40779909e-07]
 [3.40779909e-07]
 [3.40779909e-07]
 [3.40779909e-07]
 [3.40779909e-07]
 [3.407799